travis:
  secure:
    BINSTAR_TOKEN: sUgo50sNeeMiftUxdbkOvQnfXfxLokExk1sfHeGnQRJsQhKMpoKF4Ve/jXxy/y4Es2DLSHWqHFjPdQ0LpdHcMgqyYAkGulGSfvb/3f/zCYrJzFJNMGsAKYtvFugVjn06nesl2dqa1/+Uqit91ckVIByyVWF55TeADiUrM/H4E9aKpXe1zu4HoRXpEUSrBi+kOwV7U6BammHessGCel4mG58Q+OGyR/DmkMf2s5jAI9c/QDZs1EbbzKxbD5xfhYv9+AfvGMnzkpp1c+IvtYZcYUt4aZ08Clh8BZ51n4J+I+iem4JgzgMSW5Yy6GtSN5K/NY9vK8gzoEFdIzAyJUCNCB70Yt6ruYUkdP3iwCkAuIkkboR9ytWx+gZ4cBJnLZgupQfOz3cxEgFs+Flsao/t/Ta3lYJJ2qbQPqZ2QdkSe1M+zN1Hskd/0UVHawyHcd0vzNcT/rPZp+XiDkqaKjT6+Rbsu6xf4kB0+GVesTUumbik8lOaXX5mARrXQs/AhZF6jvNa4sBz2iOOMbwYyaADT4KQ2rU+Ll/wsYqknfvDKHyOuhPVPauRh73u4xEwQpNMl+pZKB1SARiL1WRdqC4OkDsec9EF5xvc3ogW2UJBfVJ3Ek72tV1zpbH5p5h0fWHmSEUae+FO7mpn8d/V8nH4CboH/09DnkHtDmnK4e89FSk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
