travis:
  secure:
    BINSTAR_TOKEN: jpX2RYoJFkbz/BfynA1UwtSpcNqHHS+xsFEcd9HTniGHS4l3dZNkJSPwguQt9VX/p0qEWUbPvuTCyWw7kKmtoYKaKH5EQSZ55sVhuAlKvjqWqYV2BEnfQd2h6AohWchrBOQY1rEPKsVqXa3S/Oqkyl1nn2r4MjbZYXEvg2otqFFy7uh767mAwv/gRnmPst8nh/Q+LHnxERW6FYeB5lmpuHaTFktrP5ua1L/ja5sbDpVtI7RY9WA6G4XMl84qkW70y/N/AxVS4XKhTPm7ZQdFnSI7kHsxyee/y4p6/GvSfujt0fSftM41eA+FVTY0adJdxVIZj8G0y1HdfCm5C5QM/pvXLKewgGznb/MQQIW4hdC8ccB2Gz29ls+RFFchkkiQguEHX/OkCc6PvD8Dnhv6enx6Cexa284w4gnXVV/33IrXOqPKDcARArO20O3IfMHgBbFU98YSFxqK0KgDBlK/Z0yS45Mt9YbvlMEI4alzR7kFg0Ynr02IGrakwlsMhGBsZJ9sHTLGySwz6AM0rsKao8YMlbFQpdWNO/YLcSaW7Jz8l19agTBAJlruy79bB8lZVH3/4AoGi76M7zn5YCgCQCN4eqogT4/c/OA/0cK39ZRqyv7zr/UaEaGcsWuyFqveFbWzrGk/2/lKtXclUAkDn1CsA8hquze1gj3rDSJticM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
