travis:
  secure:
    BINSTAR_TOKEN: ud5lo5Jhs1dyv+wE3zsQHlSz+u7NTLiKoi2xu3raRSXnACe+hNP30McwnUSB+NExM/XF8wofQSOG2AgMb0iqIcGdpavUDjTKztXftqQjVwOyxA2Gx4bSgGiSsSajm3yJBN6OuLwfSX4qdNpkmji5Gl3Kg3J+iiWkUjSEhk1XlqFlXQGfQyf7rGUTva1DKu6Iu441rNwNr2GJQy8C7My9k7TkEhQlhfSyZbDqbSsD9mPGyt69VLiDf5M3Vml84JtqLtYXmLXY0adNTGOn/a9nVIom5F0LMpRM/9dqef5a93ulnKM4ZjkrriIljpvMCvvqOLGBqORn1ZD4g7nSZKFW8vp4ml2/JiQWwC5QiqrNfLCcf0RwmnPylKChU9+zLwQwkaKtKD9cETvEPDjy1gqhBKKiz944fbx1KY2ORKJsqk7jbz2oFmGc9qID6Pqr/S/b1CBmh/PjG17lR0cNHQmXtuaVMoRIvl/zVHy2PeYvoEZN3PewKkHSX8jtphfI0iP/mBe1zb4Z/uirHibCgnPdY5G+jK1gb9KUSUykl6hDzeL1xk2B0CmFe4wJwmfTGFZiL9moAo/Vu4yo5Gqq5ScNGn+T6DtoajZ7lL/Hdq/EY7VgSVr5nY1MlVjh1u4smL0Rw0IkZMkWLxWnMr0oKyGeDPBjcqjdDBUUCViPQLgZdm4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
